services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: senior-training-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SQLSERVER_SA_PASSWORD}"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - senior_training_sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: senior-training-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - senior_training_rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  senior_training_sqlserver_data:
  senior_training_rabbitmq_data: